-- phpMyAdmin SQL Dump
-- version 4.5.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Aug 25, 2016 at 01:31 PM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 5.6.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_oxu`
--

-- --------------------------------------------------------

--
-- Table structure for table `oxu`
--

CREATE TABLE `oxu` (
  `id` int(11) NOT NULL,
  `name` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `news` text COLLATE utf8_unicode_ci NOT NULL,
  `imgName` varchar(250) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `oxu`
--

INSERT INTO `oxu` (`id`, `name`, `news`, `imgName`) VALUES
(6, 'â€œSamsung Galaxy Note 7â€-ni Ã¶ncÉ™dÉ™n sifariÅŸ edÉ™nlÉ™r â€œSamsungâ€dan hÉ™diyyÉ™lÉ™r qazanacaqlar', 'â€œSamsung Galaxy Note 7â€ â€“ adi smartfondan daha Ã¼stÃ¼n: bu cihaz Ã¶zÃ¼ndÉ™ bir Ã§ox innovasiyanÄ± birlÉ™ÅŸdirir vÉ™ mÃ¼asir aktiv istifadÉ™Ã§inin tÉ™lÉ™blÉ™rinÉ™ tam uyÄŸunlaÅŸdÄ±rÄ±lÄ±b.\r\n\r\nSmartfonun erqonomikasÄ± istifadÉ™Ã§ilÉ™r Ã¼Ã§Ã¼n rahatlaÅŸdÄ±rÄ±lÄ±b â€“ dÃ¼nyada ilk korpusunun 2 kÉ™narÄ± da qÃ¶vsvarilÉ™ÅŸdirilmiÅŸ Note. Onu tÉ™k É™ldÉ™ tutmaq vÉ™ istifadÉ™ etmÉ™k daha rahatdÄ±r.\r\n\r\nÄ°ntellektual elektron S Pen sizÉ™ daha geniÅŸ imkanlar yaradÄ±r: indi siz sÃ¼rÉ™tlÉ™ GIF-fayllar yarada vÉ™ qeydlÉ™r apara bilÉ™rsiniz, 256 GB-a qÉ™dÉ™r yaddaÅŸa malik microSD yaddaÅŸ kartlarÄ± ilÉ™ daha Ã§ox mÉ™lumat saxlamaq imkanÄ±na maliksiniz.\r\n\r\nâ€œGalaxy Note 7â€ su vÉ™ tozun tÉ™sirinÉ™ davamlÄ±dÄ±r. O suyun, tozun vÉ™ kirin tÉ™sirindÉ™n qorunub, hÉ™tta 1,5 metr dÉ™rinliyÉ™ qÉ™dÉ™r su altÄ±nda 30 dÉ™qiqÉ™yÉ™ qÉ™dÉ™r Ã§alÄ±ÅŸa bilir.\r\n\r\nSizin mÉ™lumatlarÄ±nÄ±zÄ±n daha da yaxÅŸÄ± qorunmasÄ± Ã¼Ã§Ã¼n â€œGalaxy Note 7â€ É™n rahat vÉ™ innovativ yollardan biri olan â€“ IRIS Scanner â€“ gÃ¶z bÉ™bÉ™yi skaneri ilÉ™ tÉ™chiz olunub.\r\n\r\nSiz dÉ™ â€œSamsungâ€un bu innovativ cihazÄ±nÄ±n ilk sahiblÉ™rindÉ™n biri olmaq Ã¼Ã§Ã¼n â€œBaku Electronicsâ€, â€œMaxi.azâ€, â€œKontaktâ€ vÉ™ â€œSamsungâ€ brend maÄŸaza ÅŸÉ™bÉ™kÉ™lÉ™rindÉ™n 50 manat ilkin Ã¶dÉ™niÅŸ edÉ™rÉ™k Ã¶ncÉ™dÉ™n sifariÅŸ edÉ™ bilÉ™rsiniz.\r\n\r\nAvqustun 26-dan sentyabrÄ±n 15-nÉ™ qÉ™dÉ™r Ã¶ncÉ™dÉ™n sifariÅŸ edÉ™n hÉ™r kÉ™s virtual reallÄ±q eynÉ™yi Gear VR vÉ™ 80 manat* dÉ™yÉ™rindÉ™ â€œOculusâ€ kontenti hÉ™diyyÉ™ qazanacaqlar.\r\n\r\nDaha É™traflÄ± mÉ™lumat â€œSamsung Azerbaijanâ€Ä±n â€œFacebookâ€ sÉ™hifÉ™sindÉ™.\r\n\r\n*vauÃ§erin qiymÉ™ti 50 (É™lli) ABÅž dollarÄ± ekvivalentindÉ™dir vÉ™ aksiya mÃ¼ddÉ™ti É™rzindÉ™ mÉ™zÉ™nnÉ™nin dÉ™yiÅŸilmÉ™si ilÉ™ É™laqÉ™dar olaraq vauÃ§erin manat qiymÉ™ti dÉ™yiÅŸÉ™ bilÉ™r.', '250820161257491.jpg'),
(7, 'Moskva mÉ™ktÉ™blilÉ™rinÉ™ elektron qolbaqlar verilÉ™cÉ™k', 'GiriÅŸin kartla olduÄŸu Moskva mÉ™ktÉ™blÉ™rindÉ™ kartlar silikon qolbaqlarla É™vÉ™z edilÉ™ bilÉ™r.\r\n\r\nOxu.Az xÉ™bÉ™r verir ki, bu barÉ™dÉ™ Moskva meriyasÄ±nÄ±n saytÄ±nda avqustun 25-dÉ™ mÉ™lumat yayÄ±lÄ±b. \r\n\r\nQolbaqlarÄ±n yardÄ±mÄ± ilÉ™ uÅŸaqlar mÉ™ktÉ™b yemÉ™kxanasÄ±nda naÄŸd pul istifadÉ™ etmÉ™dÉ™n yemÉ™k dÉ™ ala bilÉ™rlÉ™r.\r\n\r\nâ€œQolbaqlar 11 mÃ¼xtÉ™lif rÉ™ngdÉ™dirlÉ™r. ÃœzÉ™rindÉ™, mÉ™ktÉ™blinin elektron kartÄ±nÄ±n simvolu - balaca bayquÅŸ ÅŸÉ™kili var. \r\n\r\nBundan baÅŸqa hÉ™r bir tÉ™dris mÃ¼É™ssisÉ™si qolbaÄŸa Ã¶z loqotipini vura bilÉ™râ€, - meriyanÄ±n mÉ™lumatÄ±nda deyilir. \r\n\r\nKeÃ§É™n tÉ™dris ili É™rzindÉ™ pilot layihÉ™ Ã§É™rÃ§ivÉ™sindÉ™ qolbaqlar MoskvanÄ±n Ã¼Ã§ mÉ™ktÉ™bindÉ™ istifadÉ™ edilib. Eksperimenti uÄŸurlu adlandÄ±rÄ±blar vÉ™ kart sisteminin tÉ™tbiq olunduÄŸu digÉ™r tÉ™dris mÃ¼É™ssisÉ™lÉ™rindÉ™ dÉ™ istifadÉ™ edilmÉ™si qÉ™rara alÄ±nÄ±b. \r\n\r\nQolbaq itirildiyi halda, onu mÉ™ktÉ™bin sorÄŸusu É™sasÄ±nda bÉ™rpa etmÉ™k mÃ¼mkÃ¼n olacaq. \r\n\r\nAvqustun 20-dÉ™ RusiyanÄ±n baÅŸ naziri Dmitri Medvedev mÉ™ktÉ™b avtobuslarÄ±nÄ±n alÄ±nmasÄ± Ã¼Ã§Ã¼n pul vÉ™saitinin ayrÄ±lmasÄ±na dair sÉ™rÉ™ncam verib. 1800 nÉ™qliyyat vasitÉ™sinin alÄ±nmasÄ± Ã¼Ã§Ã¼n Ã¼Ã§ milyard rublun xÉ™rclÉ™nmÉ™si nÉ™zÉ™rdÉ™ tutulub. ', '250820161258262.jpg'),
(8, 'Avropa OyunlarÄ±nÄ±n mebellÉ™ri satÄ±lÄ±r? â€“ RÆSMÄ° AÃ‡IQLAMA', 'DÃ¼nÉ™n sosial ÅŸÉ™bÉ™kÉ™lÉ™rdÉ™ Ã¶tÉ™n il BakÄ±da keÃ§irilmiÅŸ Avropa OyunlarÄ±nÄ±n iÅŸtirakÃ§Ä±larÄ±nÄ±n yaÅŸadÄ±ÄŸÄ± Olimpiya kÉ™ndindÉ™ki mebellÉ™rin satÄ±ÅŸÄ± ilÉ™ baÄŸlÄ± xÉ™bÉ™r yayÄ±lÄ±b. SatÄ±ÅŸ haqqÄ±nda elanlarÄ±n skrin-ÅŸotlarÄ± ilÉ™ É™saslandÄ±rÄ±lmÄ±ÅŸ mÉ™lumatlar istifadÉ™Ã§ilÉ™rin narazÄ±lÄ±ÄŸÄ±na sÉ™bÉ™b olub.\r\n\r\nHaqlÄ± sual yaranÄ±b: bÉ™s 2017-ci ilin may ayÄ±nda keÃ§irilÉ™cÉ™k Ä°slam OyunlarÄ± necÉ™ olsun? MaliyyÉ™ bÃ¶hranÄ± dÃ¶vrÃ¼ndÉ™ hÉ™min yarÄ±ÅŸlar Ã¼Ã§Ã¼n yeni mebellÉ™r alÄ±nacaq? BÉ™zilÉ™ri hÉ™tta zarafatla bildirib ki, avropalÄ±larÄ±n yatdÄ±ÄŸÄ± Ã§arpayÄ±lar â€œhalalâ€ deyil vÉ™ mÃ¼sÉ™lman idmanÃ§Ä±lar Ã¼Ã§Ã¼n yeni mebel alÄ±nmalÄ±dÄ±r.\r\n\r\nOxu.Az fins.az-a istinadÉ™n bildirir ki, GÉ™nclÉ™r vÉ™ Ä°dman NazirliyindÉ™n verilÉ™n mÉ™lumata gÃ¶rÉ™, satÄ±ÅŸa Ã§Ä±xarÄ±lan mebel Olimpiya kÉ™ndindÉ™n deyil, onun yaxÄ±nlÄ±ÄŸÄ±nda yerlÉ™ÅŸÉ™n media kÉ™ndindÉ™ndir - burada xarici jurnalistlÉ™r yaÅŸayÄ±rdÄ±.\r\n\r\nâ€œÄ°slam OyunlarÄ±nda media-kÉ™nd lazÄ±m olmayacaq. JurnalistlÉ™r Ã¶z hesablarÄ±na hotellÉ™rdÉ™ qalacaqlar, - nazirliyin mÉ™tbuat katibi SÉ™mayÉ™ MÉ™mmÉ™dova bildirib. â€“ Media-kÉ™ndin binalarÄ± icarÉ™yÉ™ gÃ¶tÃ¼rÃ¼lmÃ¼ÅŸdÃ¼ vÉ™ icarÉ™nin mÃ¼ddÉ™ti bitib. MebellÉ™ri boÅŸaltmaq lazÄ±mdÄ±r vÉ™ bunlarÄ±n 25%-i satÄ±ÅŸa Ã§Ä±xarÄ±lÄ±b. YerdÉ™ qalan hissÉ™si isÉ™ nazirliyin balansÄ±nda olan ÅžÃ¼vÉ™landakÄ± uÅŸaq mÉ™rkÉ™zinÉ™ vÉ™ regionlara gÃ¶ndÉ™rilibâ€.', '250820161259193.jpg'),
(9, 'Timati: Burada azÉ™rbaycanlÄ±lar vÉ™ ermÉ™nilÉ™r normal yaÅŸayÄ±r - VÄ°DEO', 'RusiyalÄ± reper Timati TÃ¼rkiyÉ™dÉ™ konsert proqramÄ± ilÉ™ Ã§Ä±xÄ±ÅŸ edib.\r\n\r\nOxu.Az xÉ™bÉ™r verir ki, o, konsertindÉ™n olan gÃ¶rÃ¼ntÃ¼nÃ¼ â€œInstagramâ€ sÉ™hifÉ™sindÉ™ paylaÅŸÄ±b. \r\n\r\nâ€œMÉ™n Rusiya vÉ™ TÃ¼rkiyÉ™ arasÄ±nda diplomatik É™laqÉ™lÉ™rin bÉ™rpa olunmasÄ±na gÃ¶rÉ™ ÅŸadam. DÃ¼zÃ¼nÃ¼ desÉ™m, mÉ™n hÉ™tta bizim sÉ™sli konsertlÉ™rimiz Ã¼Ã§Ã¼n dÉ™ darÄ±xmÄ±ÅŸdÄ±m. Bu az olan elÉ™ yerlÉ™rdÉ™ndir ki, burada, eyni zamanda, hÉ™m ruslar vÉ™ ukraynalÄ±lar, hÉ™m ermÉ™nilÉ™r vÉ™ azÉ™rbaycanlÄ±lar, qazaxlar vÉ™ tÃ¼rklÉ™r normal gÉ™zirlÉ™râ€, - deyÉ™ reper yazÄ±b. ', '250820161300084.jpg'),
(10, 'MessencerlÉ™rin auditoriyasÄ± sosial ÅŸÉ™bÉ™kÉ™ istifadÉ™Ã§ilÉ™rinin sayÄ±nÄ± Ã¶tÃ¼b', 'DÃ¶rd É™n populyar messencer istifadÉ™Ã§ilÉ™rinin Ã¼mumi sayÄ± ilk dÉ™fÉ™ eyni sayda É™n nÃ¼fuzlu sosial ÅŸÉ™bÉ™kÉ™lÉ™rin auditoriyasÄ±nÄ± Ã¶tÃ¼b. â€œBI Intelligenceâ€ ÅŸÉ™bÉ™kÉ™ biznes resursunun mÃ¼tÉ™xÉ™ssislÉ™rinin hesablamalarÄ± buna demÉ™yÉ™ É™sas verir.\r\n\r\nOxu.Az-Ä±n mÉ™lumatÄ±na gÃ¶rÉ™, â€œICTnewsâ€ Elektron XÉ™bÉ™r XidmÉ™ti â€œvistanews.ruâ€ saytÄ±na istinadÉ™n yazÄ±r ki, portalÄ±n mÃ¼tÉ™xÉ™ssislÉ™rinin fikrincÉ™, messencerlÉ™r sosial ÅŸÉ™bÉ™kÉ™lÉ™rdÉ™n daha rahatdÄ±r.\r\n\r\nBundan baÅŸqa, onlar hesab edir ki, marketoloqlar messencerlÉ™rlÉ™ iÅŸlÉ™mÉ™yÉ™ Ã¼stÃ¼nlÃ¼k verirlÉ™r. HÉ™mÃ§inin mÉ™lumata gÃ¶rÉ™, sosial ÅŸÉ™bÉ™kÉ™lÉ™r gÉ™nc auditoriya arasÄ±nda bir o qÉ™dÉ™r populyar deyil.\r\n\r\nMÃ¼tÉ™xÉ™ssislÉ™r, hÉ™mÃ§inin bildiriblÉ™r ki, indi marketoloq vÉ™ media ÅŸirkÉ™tlÉ™ri â€œFacebookâ€ vÉ™ â€œTwitterâ€ kimi sosial ÅŸÉ™bÉ™kÉ™lÉ™rlÉ™ É™mÉ™kdaÅŸlÄ±ÄŸa Ã¼stÃ¼nlÃ¼k verir.\r\n\r\nAncaq vaxt keÃ§dikcÉ™ bu vÉ™ziyyÉ™t messencerlÉ™rin xeyrinÉ™ dÉ™yiÅŸÉ™ bilÉ™r, Ã§Ã¼nki messencerlÉ™rdÉ™ elan verÉ™nlÉ™rin istifadÉ™Ã§ilÉ™rlÉ™ qarÅŸÄ±lÄ±qlÄ± É™laqÉ™ yaratmasÄ± Ã¼Ã§Ã¼n yeni imkanlar istifadÉ™yÉ™ verilir.', '250820161300525.jpg'),
(11, 'Banklar dollar satÄ±ÅŸÄ±nÄ± bir az da mÉ™hdudlaÅŸdÄ±rdÄ± â€“ SÄ°YAHI', 'XÉ™bÉ™r verdiyimiz kimi, dollarÄ±n bahalaÅŸmasÄ± banklarda valyutanÄ±n 300-500 dollar arasÄ± limitlÉ™ satÄ±lmasÄ±na gÉ™tirib Ã§Ä±xarÄ±b. Banklar valyuta qÄ±tlÄ±ÄŸÄ±nÄ±n sÉ™bÉ™bini hÉ™rracdan ehtiyac olduÄŸu qÉ™dÉ™r xarici valyuta ala bilmÉ™mÉ™lÉ™ri ilÉ™ izah edirlÉ™r. MÉ™rkÉ™zi Bank isÉ™ kommersiya banklarÄ±nÄ±n valyuta tÉ™lÉ™blÉ™rini hÉ™rraclar vasitÉ™silÉ™ Ã¶dÉ™yÉ™ bilmÉ™dikdÉ™, É™lavÉ™ olaraq banklararasÄ± valyuta bazarÄ±na mÃ¼raciÉ™t etmÉ™yi tÃ¶vsiyÉ™ edir. \r\n\r\nOxu.Az xÉ™bÉ™r verir ki, fins.az-Ä±n araÅŸdÄ±rmalarÄ±na gÃ¶rÉ™, hazÄ±rda bÉ™zi banklar, Ã¼mumiyyÉ™tlÉ™, valyuta satÄ±ÅŸÄ±nÄ± dayandÄ±rÄ±blar. Bir qism isÉ™ limiti 100 dollara qÉ™dÉ™r azaldÄ±b. \r\n\r\nDollar satÄ±ÅŸÄ±nÄ± dayandÄ±ran vÉ™ ya limiti minimallaÅŸdÄ±ran banklar aÅŸaÄŸÄ±dakÄ±lardÄ±r:\r\n\r\nâ€œBank Respublikaâ€ - 100 dollardan yÃ¼ksÉ™k valyutanÄ±n alÄ±ÅŸ vÉ™ satÄ±ÅŸÄ±nÄ± hÉ™yata keÃ§irmir.\r\nâ€œBank Silk Veyâ€ â€“ kartlar Ã¼zrÉ™ dollar É™mÉ™liyyatlarÄ± davam etsÉ™ dÉ™, valyuta alÄ±ÅŸ-satÄ±ÅŸÄ±nÄ± tamamilÉ™ dayandÄ±rÄ±b.\r\nâ€œBank Standardâ€ - naÄŸd dollar satÄ±ÅŸÄ±nÄ± dayandÄ±rÄ±b.\r\nâ€œBank VTB (AzÉ™rbaycan)â€ - naÄŸd dollar satÄ±ÅŸÄ±nÄ± dayandÄ±rÄ±b. \r\nâ€œCaspian Development Bankâ€ - dollar satÄ±ÅŸÄ±nÄ± 200 dollar limitlÉ™ davam etdirir. \r\nâ€œExpressbankâ€ - valyutanÄ±n satÄ±ÅŸÄ±na limit tÉ™tbiq edilmÉ™sÉ™ dÉ™, mÃ¼ÅŸtÉ™rinin nÉ™ qÉ™dÉ™r hÉ™cmdÉ™ dollar almasÄ± kassadakÄ± mÉ™blÉ™ÄŸdÉ™n asÄ±lÄ±dÄ±r. YÉ™ni kassada 1000 dollar qalÄ±bsa, mÃ¼ÅŸtÉ™ri 1000 dollar, 10 dollar qalÄ±bsa, 10 dollar alacaq. \r\n â€œKapital Bankâ€ â€“ istÉ™nilÉ™n hÉ™cmdÉ™ dollar alÄ±ÅŸÄ±nÄ± aparsa da, dollar satÄ±ÅŸÄ±na 100 dollar limit tÉ™tbiq edir. \r\nâ€œMuÄŸanbankâ€ â€“ dollar satÄ±ÅŸÄ±nÄ± dayandÄ±rÄ±b. \r\nâ€œAccessbankâ€ - konvertasiyanÄ± 300 dollara qÉ™dÉ™r limitlÉ™ aparÄ±r. \r\nâ€œAFB Bankâ€ â€“ dollar satÄ±ÅŸÄ±nÄ± dayandÄ±rÄ±b. \r\nâ€œAGBankâ€ - 100 dollardan yÃ¼ksÉ™k mÉ™blÉ™ÄŸdÉ™ valyuta satmÄ±r. \r\nâ€œAmrahbankâ€ â€“ dollar satÄ±ÅŸÄ± maksimum 200 dollar tÉ™ÅŸkil edir. \r\nâ€œAtabankâ€ â€“ bu bankda da dollarÄ±n satÄ±ÅŸÄ± kassadakÄ± balansdan asÄ±lÄ±dÄ±r. Limit isÉ™ 300 dollardÄ±r. \r\nâ€œBank of Bakuâ€ â€“ bu  bankdan 300 dollar limitlÉ™ ÅŸÉ™xsiyyÉ™t vÉ™siqÉ™si tÉ™qdim etmÉ™klÉ™ dollar almaq mÃ¼mkÃ¼ndÃ¼r.\r\nâ€œTuranbankâ€ â€“ 100 dollar limitlÉ™ dollar satÄ±r. \r\nâ€œPAÅžA Bankâ€ â€“ ancaq bankÄ±n mÃ¼ÅŸtÉ™rilÉ™rinÉ™ dollar satÄ±r. Bu zaman limit tÉ™tbiq etmir. ', '250820161301426.jpg'),
(12, 'Fransada tÉ™yyarÉ™ qÉ™zasÄ±: Ã–lÉ™nlÉ™r var', 'FransanÄ±n cÉ™nub-ÅŸÉ™rqindÉ™ kiÃ§ik tÉ™yyarÉ™nin qÉ™zaya uÄŸramasÄ± nÉ™ticÉ™sindÉ™ iki nÉ™fÉ™r Ã¶lÃ¼b.\r\n\r\nOxu.Az TASS-a istinadÉ™n xÉ™bÉ™r verir ki, hadisÉ™ Ã¶lkÉ™nin Sen-Remi-de-Moren ÅŸÉ™hÉ™rciyindÉ™ olub.\r\n\r\nÅžÉ™hÉ™r valisi bildirib ki, uÃ§uÅŸ zamanÄ± iki nÉ™fÉ™rlik tÉ™yyarÉ™ aÄŸaca iliÅŸib vÉ™ qÉ™za baÅŸ verib.\r\n\r\nTÉ™yyarÉ™nin gÃ¶yÉ™rtÉ™sindÉ™ki iki nÉ™fÉ™rin turist olduÄŸu ehtimal edilir.', '250820161302207.jpg'),
(13, 'Vergi Ã¶dÉ™yicilÉ™rinÉ™ ÅŸans verilÉ™cÉ™k â€“ YENÄ°LÄ°K', 'AzÉ™rbaycan Prezidenti Ä°lham Æliyevin 4 avqust tarixli â€œ2016-cÄ± ildÉ™ vergi sahÉ™sindÉ™ aparÄ±lacaq islahatlarÄ±n istiqamÉ™tlÉ™riâ€nin tÉ™sdiqi vÉ™ vergi inzibatÃ§Ä±lÄ±ÄŸÄ±nÄ±n tÉ™kmillÉ™ÅŸdirilmÉ™si haqqÄ±nda SÉ™rÉ™ncamÄ±nda diqqÉ™t Ã§É™kÉ™n mÉ™qamlardan biri dÉ™ vergi Ã¶hdÉ™liklÉ™rinin É™vvÉ™lcÉ™dÉ™n mÃ¼É™yyÉ™nlÉ™ÅŸdirilmÉ™si (â€œAdvance tax rulingâ€) qaydasÄ±nÄ±n tÉ™tbiqidir. \r\n\r\nHÉ™min sistem inkiÅŸaf etmiÅŸ Ã¶lkÉ™lÉ™rdÉ™ istÉ™r fÉ™rdi vergi Ã¶dÉ™yicilÉ™ri, istÉ™rsÉ™ dÉ™ iri ÅŸirkÉ™tlÉ™r Ã¼Ã§Ã¼n geniÅŸ istifadÉ™ edilÉ™n alÉ™tlÉ™rdÉ™ndir.\r\n\r\nBu zaman vergi Ã¶dÉ™yicilÉ™rinin mÃ¼raciÉ™ti É™sasÄ±nda vergi orqanlarÄ± qanunuvericilikdÉ™ nÉ™zÉ™rdÉ™ tutulmuÅŸ qaydada hÉ™min vergi Ã¶dÉ™yicisinin É™mÉ™liyyatlarÄ± Ã¼zrÉ™ yarana bilÉ™cÉ™k vergi Ã¶hdÉ™liyi barÉ™dÉ™ mÉ™lumat hazÄ±rlayaraq ona tÉ™qdim edirlÉ™r. \r\n\r\nBu barÉ™dÉ™ Oxu.Az-a VergilÉ™r NazirliyindÉ™n bildirilib.\r\n\r\nMÉ™lum olduÄŸu kimi, sahibkarlarÄ±n hÉ™r hansÄ± sÉ™bÉ™bdÉ™n vergi Ã¶hdÉ™liklÉ™rini dÃ¼zgÃ¼n mÃ¼É™yyÉ™n etmÉ™mÉ™si nÉ™ticÉ™sindÉ™ Vergi MÉ™cÉ™llÉ™sindÉ™ nÉ™zÉ™rdÉ™ tutulmuÅŸ qaydada mÉ™suliyyÉ™tÉ™ sÉ™bÉ™b olur. \r\n\r\nYÉ™ni hÉ™min ÅŸÉ™xsÉ™ maliyyÉ™ sanksiyalarÄ± vÉ™ faizlÉ™r hesablanÄ±r vÉ™ o, maliyyÉ™ sanksiyalarÄ± vÉ™ faizlÉ™ri Ã¶dÉ™mÉ™klÉ™ dÃ¶vriyyÉ™ vÉ™saitindÉ™n sÉ™mÉ™rÉ™li istifadÉ™ edÉ™ bilmir, son nÉ™ticÉ™dÉ™ ciddi maliyyÉ™ itkilÉ™ri ilÉ™ Ã¼zlÉ™ÅŸir. \r\n\r\nBelÉ™ hallarÄ±n qarÅŸÄ±sÄ±nÄ±n alÄ±nmasÄ±na kÃ¶mÉ™k edÉ™n Ã¼sullardan biri dÉ™ vergi Ã¶dÉ™yicilÉ™ri tÉ™rÉ™findÉ™n aparÄ±lmasÄ± planlaÅŸdÄ±rÄ±lan É™mÉ™liyyatlar Ã¼zrÉ™ vergi Ã¶hdÉ™liklÉ™rinin É™vvÉ™lcÉ™dÉ™n mÃ¼É™yyÉ™nlÉ™ÅŸdirilmÉ™si mexanizminin hazÄ±rlanmasÄ±dÄ±r.\r\n\r\nHazÄ±rda vergi Ã¶hdÉ™liklÉ™rinin hÃ¼quqi nÉ™ticÉ™lÉ™r doÄŸurmadan vergi orqanlarÄ± ilÉ™ razÄ±laÅŸdÄ±rÄ±lmasÄ± qaydasÄ±nÄ±n mÃ¼É™yyÉ™n edilmÉ™si ilÉ™ baÄŸlÄ± qanunvericiliyÉ™ dÉ™yiÅŸikliklÉ™r layihÉ™si Ã¼zÉ™rindÉ™ iÅŸ gedir.\r\n\r\nSÉ™rÉ™ncÉ™ma É™sasÉ™n, hÉ™r bir vergi Ã¶dÉ™yicisinÉ™ Ã¶z sÉ™hvlÉ™rini kÃ¶nÃ¼llÃ¼ aÃ§Ä±qlamaq ÅŸansÄ± da yaradÄ±lÄ±r. Bu, â€œKÃ¶nÃ¼llÃ¼ vergi aÃ§Ä±qlamasÄ±â€ (â€œVoluntary tax disdosure") sisteminin tÉ™tbiqi ilÉ™ baÄŸlÄ±dÄ±r. KÃ¶nÃ¼llÃ¼ vergi aÃ§Ä±qlamasÄ±, vergi yoxlamasÄ± Ã¼Ã§Ã¼n qanunla mÃ¼yyÉ™n edilmiÅŸ mÃ¼ddÉ™t  bitdikdÉ™n sonra, yoxlama zamanÄ± aÅŸkar olunmamÄ±ÅŸ sÉ™hvlÉ™rin kÃ¶nÃ¼llÃ¼ bÉ™yan edilmÉ™sini nÉ™zÉ™rdÉ™ tutur. \r\n\r\nBununla da vergi Ã¶dÉ™yicisinin dÉ™qiqlÉ™ÅŸmiÅŸ bÉ™yannamÉ™ vermÉ™k hÃ¼ququ yaranacaq vÉ™ hÉ™min bÉ™yannamÉ™ ilÉ™ kÃ¶nÃ¼llÃ¼ aÃ§Ä±qlanmÄ±ÅŸ vergi mÉ™blÉ™ÄŸlÉ™rinÉ™ gÃ¶rÉ™ faizlÉ™rin hesablanmasÄ± vÉ™ maliyyÉ™ sanksiyasÄ±nÄ±n tÉ™tbiqi istisna edilÉ™cÉ™k.\r\n\r\nMÃ¼tÉ™xÉ™ssislÉ™rin qÉ™naÉ™tinÉ™ gÃ¶rÉ™, sÉ™rÉ™ncama uyÄŸun olaraq hÉ™yata keÃ§irilmÉ™si nÉ™zÉ™rdÉ™ tutulan tÉ™dbirlÉ™r vergi inzibatÃ§Ä±lÄ±ÄŸÄ±nÄ±n beynÉ™lxalq tÉ™lÉ™blÉ™rÉ™ tam uyÄŸunlaÅŸdÄ±rÄ±lmasÄ±na vÉ™ digÉ™r Ã¶lkÉ™lÉ™rin qabaqcÄ±l tÉ™crÃ¼bÉ™lÉ™rinin AzÉ™rbaycanda daha geniÅŸ tÉ™tbiqinÉ™ ÅŸÉ™rait yaradacaq.', '250820161302588.jpg'),
(14, 'BilÉ™suvarda ÆsgÉ™rabad-MuÄŸan-Ã‡aylÄ± avtomobil yolunun tikintisi baÅŸa Ã§atÄ±b', 'BilÉ™suvar rayonu ÆsgÉ™rabad-MuÄŸan-Ã‡aylÄ± avtomobil yolunun tikinti iÅŸlÉ™ri yekunlaÅŸÄ±b.\r\n\r\nOxu.Az xÉ™bÉ™r verir ki, â€œAzÉ™ravtoyolâ€ ASC-dÉ™n verilÉ™n mÉ™lumata gÃ¶rÉ™, ÆsgÉ™rabad-MuÄŸan-Ã‡aylÄ± avtomobil yolunun uzunluÄŸu 6 kilometrdir vÉ™ II texniki dÉ™rÉ™cÉ™yÉ™ uyÄŸun olaraq tamamilÉ™ yeni tras Ã¼zrÉ™ layihÉ™lÉ™ndirilib.\r\n\r\nLayihÉ™yÉ™ uyÄŸun olaraq sÃ¶zÃ¼gedÉ™n yolun hÉ™rÉ™kÉ™t hissÉ™sinin eni 9 metr, hÉ™rÉ™kÉ™t zolaqlarÄ±nÄ±n eni 3,75 metr, Ã§iyinlÉ™rin eni 3 metr, torpaq yataÄŸÄ±nÄ±n eni isÉ™ 15 metrdir. Yolda eninÉ™ maillik hÉ™rÉ™kÉ™t hissÉ™sindÉ™ 2%, Ã§iyinlÉ™rdÉ™ isÉ™ 4%-dir. ÆsasÄ±n alt layÄ± â€“ optimal Ã§Ä±nqÄ±l qarÄ±ÅŸÄ±ÄŸÄ±, qalÄ±nlÄ±ÄŸÄ± 24 sm, É™sasÄ±n Ã¼st layÄ± optimal qÄ±rmadaÅŸ qarÄ±ÅŸÄ±ÄŸÄ±, qalÄ±nlÄ±ÄŸÄ± 16 sm vÉ™ asfalt-beton Ã¶rtÃ¼k 3 laydan ibarÉ™t qalÄ±nlÄ±ÄŸÄ± 25 sm olmaqla yol geyiminin konstruksiyasÄ±nÄ±n qalÄ±nlÄ±ÄŸÄ± 65 sm tÉ™ÅŸkil edir.\r\n\r\nLayihÉ™yÉ™ uyÄŸun olaraq yolun 1,68 kilometrliyindÉ™ Balhari Ã§ayÄ± Ã¼zÉ™rindÉ™ 3 aÅŸÄ±rÄ±mlÄ±, uzunluÄŸu 81,3 metr olan avtomobil kÃ¶rpÃ¼sÃ¼ inÅŸa edilib. Bundan baÅŸqa, 7 yerdÉ™ Ã¼mumi uzunluÄŸu 170 metr olan  dairÉ™vi boru, 3 yerdÉ™ dÃ¼zbucaqlÄ± Ã¼mumi uzunluÄŸu 73 metr olan boru, 2 yerdÉ™  Ã¼mumi uzunluÄŸu 47 metr olan dÃ¼zbucaqlÄ± su keÃ§idi, hÉ™mÃ§inin 9 yerdÉ™ yol birlÉ™ÅŸmÉ™lÉ™ri vÉ™ biri dairÉ™vi olmaqla 3 yol kÉ™siÅŸmÉ™si inÅŸa edilib. \r\n\r\nLayihÉ™ Ã§É™rÃ§ivÉ™sindÉ™ avtonÉ™qliyyat vasitÉ™lÉ™rinin normal hÉ™rÉ™kÉ™tinin tÉ™nzimlÉ™nmÉ™si mÉ™qsÉ™di ilÉ™ 18 780 metr uzunluÄŸunda yol cizgi vÉ™ yol gÃ¶stÉ™rici xÉ™tlÉ™ri Ã§É™kilib, zÉ™ruri olan yerlÉ™rdÉ™ 30 iÅŸÄ±q dirÉ™yi, 186 É™dÉ™d yol tÉ™hlÃ¼kÉ™sizlik dirÉ™klÉ™ri, 94 É™dÉ™d mÃ¼xtÉ™lif yol niÅŸanlarÄ± quraÅŸdÄ±rÄ±lÄ±b, hÉ™mÃ§inin tikinti sahÉ™sinÉ™ dÃ¼ÅŸÉ™n 376 metr qaz vÉ™ su borusunun kÃ¶Ã§Ã¼rÃ¼lmÉ™si iÅŸlÉ™ri aparÄ±lÄ±b.\r\n\r\nÆsgÉ™rabad-MuÄŸan-Ã‡aylÄ± avtomobil yolunun tikintisindÉ™ mÉ™qsÉ™d M-3 ÆlÉ™t-Astara-Ä°ran sÉ™rhÉ™di magistral avtomobil yolu ilÉ™, R-43 BilÉ™suvar-Ä°ran sÉ™rhÉ™di vÉ™ R-42 BÉ™hramtÉ™pÉ™-BilÉ™suvar avtomobil yollarÄ±nÄ± birlÉ™ÅŸdirÉ™rÉ™k BilÉ™suvar rayon mÉ™rkÉ™zinÉ™ daxil olmadan dairÉ™vi yol kimi yÃ¼k vÉ™ sÉ™rniÅŸin daÅŸÄ±masÄ±nÄ± tÉ™min etmÉ™kdir. \r\n\r\nEyni zamanda, sÃ¶zÃ¼gedÉ™n yol vasitÉ™si ilÉ™ 10 mindÉ™n artÄ±q É™halisi olan ÆsgÉ™rabad, MuÄŸan vÉ™ Ã‡aylÄ± yaÅŸayÄ±ÅŸ mÉ™ntÉ™qÉ™lÉ™rinÉ™ dÉ™ nÉ™qliyyat xidmÉ™ti tÉ™min edilÉ™cÉ™k.\r\n\r\nQeyd edÉ™k ki, bundan Ã¶ncÉ™ bu yaÅŸayÄ±ÅŸ mÉ™ntÉ™qÉ™lÉ™rinÉ™ nÉ™qliyyatÄ±n hÉ™rÉ™kÉ™ti ancaq BilÉ™suvar ÅŸÉ™hÉ™rinin daxili yollarÄ± vasitÉ™si ilÉ™ tÉ™ÅŸkil olunurdu.', '250820161303469.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `oxu`
--
ALTER TABLE `oxu`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `oxu`
--
ALTER TABLE `oxu`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
